local utils = require 'luncheon.utils'
local MockSocket = require 'spec.mock_socket'.MockSocket

describe('utils', function ()
    describe('send_all', function ()
        it('sends', function ()
            local sock = MockSocket.new()
            assert.is.equal(utils.send_all(sock, 'asdf'), 4)
        end)
        it('retries on timeout', function ()
            local sock = MockSocket.new()
            assert.is.equal(utils.send_all(sock, 'timeout2'), 8)
        end)
        it('retries on panic', function ()
            local sock = MockSocket.new()
            assert.is.equal(utils.send_all(sock, 'panic'), 5)
        end)
        it('errors on closed', function ()
            local sock = MockSocket.new()
            local n, e = utils.send_all(sock, 'closed')
            assert.is.falsy(n)
            assert.are.equal('Attempt to send on closed socket', e)
        end)
    end)
end)
